CHANGELOG.md, Configuration/TCA/Overrides/sys_template.php
The registration had accidentally been removed by some
previous changes.
=> [BUGFIX] Re-add the static TypoScript registration

CHANGELOG.md, Configuration/TCA/tx_tea_domain_model_product_tea.php
This option has been removed in TYPO3 7.
Resolves #43
=> [CLEANUP] Drop obsolete dividers2tabs from the TCA

CHANGELOG.md, README.md
Now that the project has been moved to a different project,
the GitHub actions status badge URL needs to be adapted.
=> [TASK] Update the GitHub actions status badge URL

.github/workflows/ci.yml, CHANGELOG.md
For GitHub actions, an explicit step is required to use a
specific PHP version. If this is not done, a default version
will be used (which makes the builds unpredictable).
=> [BUGFIX] Use the PHP version from the matrix in the CI

.travis.yml, CHANGELOG.md
Downgrades of Composer packages do not work reliably
if a higher version of a package already is installed in `vendor/`.
This causes builds to use higher versions of packages than intended
if Travis CI has the corresponding version in the cached and restored
`vendor/` folder.
=> [BUGFIX] Stop caching vendor/ on Travis CI

CHANGELOG.md, composer.json
To avoid stating any untested compatibility with a (non-existent) PHP
version 7.5, the requirements in the `composer.json` need to provide
the patch-level version as well as `~7.0` works the same as `^7.0`,
while `~7.0.0` does not.
=> [BUGFIX] Avoid unwanted higher PHP versions

.github/workflows/ci.yml, CHANGELOG.md
This currently is broken, and we need to find the cause and fix it
first.
In the meantime, disable this so the build is green again.
=> [TASK] Disable running with lower dependencies on GitHub actions

CHANGELOG.md, composer.json
Add the full relative path to Composer-installed binaries to make
sure that are used instead of other versions that happen to be in
the path.
Also drop unneeded trailing slashes from directories used in
Composer scripts.
=> [BUGFIX] Always use the Composer-installed tools

composer.json
There is a bug in reflection-docblock package in version 5.2.0. This version of package breaks functional tests. We have to wait for T3 bugfix.
=> [TASK] Set reflection docblock version to avoid bug in package

README.md
We only want to see whether the build for the current default branch
is successful, not the status of any other branches or PRs.
Also make the alt text for the badge more specific as we now have
two CI builds (GitHub and GitLab).
=> [BUGFIX] Only show the default branch status in the CI badge

.github/workflows/ci.yml, .gitlab/pipeline/.gitlab-ci.yml
- drop the `--no-suggest` option that was deprecated in Composer 2
- output the Composer version to make debugging problems easier
=> [TASK] Smoothen the way to Composer 2

.gitlab/pipeline/.gitlab-ci.yml
secrets-sast was removed from SAST vendored template
https://gitlab.com/gitlab-org/gitlab/-/issues/234011
we need to migrate to separate template, it's breaking gitlab ci template ATM, as it's moved out and it won't work anymore
=> Migrate secret detection in gitlab ci

.gitlab/pipeline/.gitlab-ci.yml
Change way to inherit default settings. Migrate to ``` extends ``` in order to avoid any issues with gitlab templates.
https://gitlab.typo3.org/qa/example-extension/-/pipelines/9983
=> Fix to gitlab regression

.github/workflows/ci.yml, CHANGELOG.md
This will allow us to catch problems with dependencies or
the build environment, i.e., problems that are not related
to changes in our code base.
=> [FEATURE] Also run the CI build once a week

.editorconfig
`*.ts` are TypeScript files, not TypoScript files.
=> [BUGFIX] Stop treating *.ts files as TypoScript in the .editorconfig

.github/workflows/ci.yml, .gitlab/pipeline/.gitlab-ci.yml
Progress bars do not make sense when the output is logged
(like on GitHub actions).
=> [TASK] Stop displaying a progress bar during composer require

.github/workflows/ci.yml, composer.json
- fix a syntax error in the `ci.yml`
- also update/downgrade transitive dependencies
- add a conflict with broken versions of typo3/class-alias-loader
- use a Composer-2-compatible version of `helhum/typo3-composer-setup`
- start running the unit and functional tests with the lowest
dependencies on GitHub Actions
Fixes #50
=> [BUGFIX] Fix the CI build with the lowest dependencies

.github/workflows/ci.yml
This fixes a warning when running the CI build.
As the functional tests currently do not run with the Ubuntu 20.04
runner, we need to keep using 18.04.
Also explicitly require the `mysqli` PHP extension.
=> [BUGFIX] Explicitly set the Ubuntu version for GitHub Actions

composer.json
This will reduce unrelated changes when requiring new packages
(as the `composer.json` is configured to keep the requirements
sorted).
=> [CLEANUP] Sort the requirements in the composer.json

.github/workflows/ci.yml
This avoid problems with Xdebug 3 (the version that now automatically
gets installed).
=> [BUGFIX] Disable Xdebug in the CI build

.github/workflows/ci.yml
Even if a job fails with e.g., a certain PHP version, we still want to
know if it succeeds with which other PHP versions.
=> [TASK] Always run all CI jobs

.github/workflows/ci.yml, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf
This now matches what the TYPO3 Core uses.
We still use the XLIFF 1.2 schema for validation as version 1.2
is the first fully ratified version.
Closes #198
=> [BUGFIX] Downgrade the XLIFF files to version 1.0

.github/workflows/ci.yml
I prepared github action for typoscript linting, migrate tea extension to use it as example
https://github.com/TYPO3-Continuous-Integration/TYPO3-CI-Typoscript-Lint
=> [TASK] Migrate TypoScript linting to a GitHub action

composer.json
Now the `ci:php` and `ci:static` Composer commands call all commands
that belong in those groups.
=> [TASK] Complete the ci:php and ci:static Composer commands groups

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf
Now that the Core uses XLIFF version 1.2, this extension
should do so (again), too.
This reverts commit e51dad6aeaca1859b9f8198a179f2134f18fcdef.
=> [TASK] Re-upgrade the XLIFF files to version 1.2

.editorconfig
The indentation of 4 spaces for Markdown and XML files already is
set via the default configuration in the `.editorconfig`.
Fixes #244
=> [TASK] Limit the line length for Markdown files via `.editorconfig`

composer.json
Is there any case in which using php-cli is required here? I can execute them locally without any problems. We are not setting php in php-cs-fixer fix anyway. Maybe we could get rid of those?
=> [TASK] Remove php occurencies in lint scripts

.gitlab/pipeline/.gitlab-ci.yml
GitLab offers default jobs for LicenseManagement, SecretDetection and SAST which are used here. However since some versions the filename of these includes was adapted and harmonised. Running the current files creates no pipelines due to a YAML error, as these includes are not found.
=> [BUGFIX] Fix default template names for GitLab CI

README.md, composer.json
Adds the command `docs:generate` to `composer.json`.
Tested on macOS 11.5.2 (M1) and Docker 20.10.7.
=> [FEATURE] Composer command for rendering documentation

README.md, composer.json
Composer has a built-in functionality for describing Composer scripts,
and we should use it for documentating our custom scripts.
=> [TASK] Move the Composer script descriptions to the `composer.json`

.github/workflows/ci.yml, .github/workflows/predefined.yml, README.md
Also stop running the other CI workflow on every push/PR
(as the results of both workflows provide the same results).
Fixes #275
=> [TASK] Use the Composer scripts for the CI builds by default

composer.json
- make the app dir explicit
- allow the root project to be used as an extension
(this fixes the test in TYPO3 >= 11.4)
=> [BUGFIX] Complete the `typo3/cms` section in the `composer.json`

.phpstorm.meta.php
Add PhpStorm meta file for autocomplete of `GeneralUtility::makeInstance`, `getAccessibleMock` and `getAccessibleMockForAbstractClass` in unit tests
=> [TASK] Add PhpStorm meta file

.github/workflows/ci.yml
If the CI build will do a composer update in the next step anyway,
there is no need to actually install any packages when requiring
the desired TYPO3 version.
Fixes #324
=> [TASK] Only install Composer packages once in a CI build

.github/workflows/publish.yml, CHANGELOG.md
Tags named like `test-tag` should not trigger a TER releasen, but only
valid version numbers in the format major.minor.bugfix.
Fixes #327
=> [BUGFIX] Only publish to the TER if the tag is a valid version number

CHANGELOG.md, composer.json
This fixes a missing Symfony polyfill for `str_starts_with` in
TYPO3 11.5.0 and 11.5.1, which fixes a crash in the unit tests with
TYPO3 11LTS and PHP 7.4 using the lowest possible Composer dependencies.
=> [BUGFIX] Require at least TYPO3 11.5.2 for 11LTS

composer.json
This package is no longer needed for running the tests with
modern TYPO3 versions.
=> [TASK] Drop the `helhum/typo3-composer-setup` dev dependency

phpcs.xml
The previous configuration disallowed newlines in ternary operator like:
```
$a = $condition1 && $condition2
? $foo_man_this_is_too_long_what_should_i_do
: $bar;
```
This seems very arbitrary since breaking on other operators is in fact
allowed.
This change allows such longer statements to be broken apart over
several lines.
Fixes #337
=> [TASK] allow newlines for ternary operator

README.md
The badge behaves in an unpredictable way if there are mutiple unstable
releases (which happens when we update the branch alias for the `main`
branch) and hence is pretty much useless.
=> [TASK] Drop the badge for unstable releases from the README

.ddev/config.yaml, .github/workflows/ci.yml, .github/workflows/codecoverage.yml, .github/workflows/predefined.yml
Composer versions 2.2.0 and 2.2.1 have a bug that breaks PHPUnit.
Until version 2.2.2 is released with a fix, we need to keep to
Composer 2.1 to keep the tests from breaking.
See https://github.com/composer/composer/issues/10387 for details.
=> [BUGFIX] Pin Composer to version 2.1.x

.github/workflows/ci.yml
This will allow us to test things on the CI pipeline without
having to create a dummy/draft PR for this.
Hopefully, this will also allow builds for forks.
=> [TASK] Always run the CI build after a push

composer.json
This will allow Composer plugins like composer-normalize to run
in Composer >= 2.2 as well.
=> [BUGFIX] Explicitly allow the development Composer plugins

.github/workflows/ci.yml, .github/workflows/codecoverage.yml, .github/workflows/predefined.yml
With the releases of Composer 2.2.2 and 2.2.3 (and PHPUnit 9.5.11),
running the tests with Composer 2 in the pipeline should be safe afain.
=> [TASK] Use Composer 2.2 in the CI pipeline

.github/workflows/ci.yml
It has turned out that having builds only for pushes (but not
pull requests) is not enough for triggering builds for PRs
from forks.
So we will need to live with pushes to non-PR branches other
than main not triggering a build, and having to create a
dummy draft PR for testing the CI build.
This reverts commit d1f02afe7975c6f66221077aca077f71f84bcbdf.
Fixes #359
=> [BUGFIX] Fix CI builds for PRs from forks

.github/workflows/ci.yml, CHANGELOG.md, composer.json, ext_emconf.php
Now that we have added support for TYPO3 11LTS, we have been supporting
3 different TYPO3 LTS versions in the same branch. This has turned out
to be too much of a hassle when running the test. So now is the time
to drop support for 9LTS.
=> [TASK] Drop support for TYPO3 9LTS

composer.json
Version 3.5.0 has a bug concerning intersection types that breaks our
build.
Fixes #368
=> [BUGFIX] Avoid php-cs-fixer 3.5.0

composer.json
xargs shell command will throw an error if find command will return an empty result. Adding -r will prevent this error. 
Example: 
A project has no yml files.
Before: The yaml-linting fails.
With that patch: The yaml-linting succeed.
=> [BUGFIX] Avoid xargs error for empty project

CHANGELOG.md, README.md
We should not advertise what we're not supporting anymore.
=> [TASK] Drop the TYPO3 V9 badge

.gitlab/build/docker_install.sh, .gitlab/pipeline/jobs/func-php7.2-v10.yml, .gitlab/pipeline/jobs/func-php7.2-v9.yml, .gitlab/pipeline/jobs/func-php7.3-v10.yml, .gitlab/pipeline/jobs/func-php7.3-v9.yml, .gitlab/pipeline/jobs/func-php7.4-v10.yml, .gitlab/pipeline/jobs/func-php7.4-v9.yml
It might happen, when starting the fuctional test that the database service container is not ready yet. 
This patch provides an extra timeout to wait for the service to make sure the test does not fail because of missing database.
=> [BUGFIX] install and use wait-for-it for functional tests

.gitignore
- `.php_cs.cache` file was renamed to `.php-cs-fixer.cache`
- `.phpunit.result.cache` missing in `.gitignore`
=> [BUGFIX] Fix some `.gitignore` entries

Configuration/TCA/tx_tea_domain_model_product_tea.php
This entry was deprecated in TYPO3 10.3:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-88901-RenderAllFieldsInElementInformationController.html
Fixes #384
=> [BUGFIX] Remove `showRecordFieldList` from the TCA

Configuration/TCA/Overrides/tt_content.php, ext_localconf.php
This has been deprecated in TYPO3 10.0:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-87550-UseControllerClassesWhenRegisteringPluginsmodules.html
Fixes #383
=> [BUGFIX] Stop using the vendor name for plugin registration

Configuration/TCA/tx_tea_domain_model_product_tea.php
This version switch was releveant for TYPO3 8LTS.
=> [TASK] Remove an obsolete version switch from the TCA configuration

.phpstorm.meta.php, README.md, Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php, Tests/Unit/Controller/TeaControllerTest.php, Tests/Unit/Domain/Model/Product/TeaTest.php, Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php, composer.json
The TYPO3 core testing framework has more person-power for maintenance
behind it compared to the nimut testing framework. So we should use that.
=> [TASK] Switch to the core testing framework

.github/workflows/ci.yml, .github/workflows/predefined.yml
This will allow use to have exceptions from the cross product of
the parameters more easily (e.g., using PHP 8 only for TYPO3 11LTS
onward).
=> [TASK] Use an explicit CI matrix for the functional tests as well

.github/workflows/ci.yml, .github/workflows/predefined.yml
This helps human readers see what a job is about more quickly,
following the principle of having the heading as the first element
of a text.
=> [CLEANUP] Always have the CI job name as first element

.github/workflows/predefined.yml
The CI workflow with predefined GitHub actions had an empty `on:`
element, which is invalid. Use the correct event for manually
triggered workflow runs instead.
=> [BUGFIX] Fix the trigger syntax in the CI builds

.github/workflows/ci.yml
`json:lint` was there twice.
Also sort the code quality jobs the same way the corresponding tasks
are sorted in the `composer.json`.
=> [BUGFIX] Remove duplicate entry from the code quality CI job

.github/workflows/ci.yml, .github/workflows/codecoverage.yml, .github/workflows/predefined.yml
The installed Composer packages will be different depending on the
major TYPO3 version being tested and on the strategy for the
dependencies (highest, lowest). So it makes sense to have
separate Composer caches for these versions in order to avoid
cache misses.
=> [TASK] Make the Composer caches on CI more fine-grained

Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php, Configuration/Services.yaml, Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
`ObjectManager` is deprecated in V11.
Fixes #387
=> [BUGFIX] Configure DI and avoid using `ObjectManager` in TYPO3 11LTS

composer.json
phpcpd gives a lot of false positives (in the sense that the code can't be changed or it does not make sense to change it) in TCA definitions and tests.
Resolves #410
=> [BUGFIX] Remove folders `Config` and `Tests` from phpcpd call

.github/workflows/codecoverage.yml
We should use the latest TYPO3 and PHP versions for code coverage
generation.
=> [TASK] Bump the code coverage generation to TYPO3 11LTS and PHP 8.1

Documentation/Settings.cfg
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/185
=> [DOCS] Reference manual's start page with :doc:`<manual>:Index`

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
This avoids potential false results in the tests because it doesn't add additional restrictions for starttime, endtime, deleted, and hidden.
Fixes #421
=> [BUGFIX] Use `executeQuery()` in functional test example

.github/workflows/codecoverage.yml, composer.json
There is no need to have the code coverage data directly generated by
the tests run in a non-hidden directory. So now the code coverage is
recorded within `.Build/coverage`.
Only the merged coverage data still needs to be located in `build/logs`
as Coveralls (which we're planning to use) relies on this.
=> [TASK] Move the coverage directories

.gitlab/pipeline/jobs/build-composer-dependencies.yml
We must not cache this directory. If it is cached, this might cause
Composer to (re-)install dependency version that are not valid for
the current PHP version, which possibly might break the build.
=> [BUGFIX] Do not cache the `.Build` directory in GitLab CI

.github/workflows/codecoverage.yml
Having a consistent structure and order between the CI jobs and the
code coverage generation job makes understanding the GitHub Actions
configuration easier.
It also allows having a shared Composer cache between the non-coverage
jobs and the coverage job.
=> [TASK] Sync the GitHub Actions job definitions

README.md
Reorder the badges so the TYPO3 versions come first and the
CI information latest (ordered from user-relevant to
developer-relevant).
Drop some badges to get the badges to fit in one line again:
- Drop the counter for this month's downloads (as this number
fluctuated too much during the month).
- Drop a duplicate badge.
- Drop the badge for the old CoC (as we now are using the TYPO3 CoC).
- Drop the "latest version" badge (as this tends to be unreliable).
=> [TASK] Reduce and reorder the badges in the README

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
We currently can only test the lazy loading of the model image
with a functional test that retrieves a model from the database
via the repository.
So the functional test for the repository also needs to be marked as
covering the model class to make our code coverage correct.
=> [BUGFIX] Mark the repository test as also covering the model

.github/dependabot.yml, CHANGELOG.md
With this configuration, GitHub's Dependabot will create PR
to update the versions of the GitHub Actions we are using in
our CI pipeline.
=> [FEATURE] Add a Dependabot action for updating GitHub actions

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
As in these cases the type annotations from the base class are used,
we can avoid PHPStan warnings about discrepancies between our annotations
and the annotations from the testing framework for the corresponding
fields in the superclass.
=> [CLEANUP] Remove type annotations for fields from the testing framework

.github/workflows/ci.yml, .github/workflows/codecoverage.yml, .github/workflows/predefined.yml
PHP version numbers need to be strings: If the version `8.0` were
treated as a number, the YAML parser would happily convert it to `8`,
hence dropping the minor version number.
=> [BUGFIX] Treat PHP versions in the GitHub CI configuration as strings

CHANGELOG.md, composer.json, phpstan-baseline.neon
We want PHPStan to be as strict as possible.
(The new warning requires a change in Extbase to get solved properly.)
=> [TASK] Add the PHPStan strict rules

.github/dependabot.yml
composer-noramlize >= 2.2.0 will conflicts with our supported PHP
version range, as does PHPUnit 9.x (and 10.x will too).
So we need to configure Dependabot to stay below these breaking
versions.
Fixes #467
=> [BUGFIX] Block Dependabot from breaking upgrades

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
We are not using any "container" class here, and hence the results from
repository find methods should be named `$result` instead of `$container`.
=> [TASK] Change misleading variable names in some tests

Classes/Domain/Repository/Product/TeaRepository.php, phpstan-baseline.neon
This avoids PHPStan warnings in a case where our type annotations are
not up to date anymore with the latest change in the Core.
=> [BUGFIX] Do not overwrite type annotations from parent classes

composer.json
~8.0 means >= 8.0.0 < 9.0.0
~8.1 means >= 8.1.0 < 9.0.0
What really is wanted:
~8.0.0 means >= 8.0.0 < 8.1.0
~8.1.0 means >= 8.1.0 < 8.2.0
See: https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
=> [BUGFIX] Correct version constraints for PHP in composer.json

CHANGELOG.md, composer.json
PHPUnit has dropped its dependency on Prophecy. In order to keep using
Prophecy in our tests, we need to add it as an explicit (development)
dependency.
Also, relying on transitive dependencies is bad practice anyway.
=> [BUGFIX] Explicitly require Prophecy

.ddev/config.yaml, .github/workflows/ci.yml, .github/workflows/codecoverage.yml, .github/workflows/predefined.yml, CHANGELOG.md
Now that Composer 2.4 has had its first point release, we can safely
upgrade from 2.3 to 2.4 in the DDEV configuration and the CI pipeline.
=> [TASK] Update to Composer 2.4

.github/workflows/ci.yml, .github/workflows/codecoverage.yml, .github/workflows/predefined.yml
The `typo3/minimal` package is not maintained very much, and currently
cannot be used as a requirement to install the latest TYPO3 development
version (as it still depends on `dev-master`, not on `dev-main`).
In addition, not depending on it will allow us to find any missing
dependencies in our requirements that so far have been masked by
the `typo3/minimal` dependencies.
=> [TASK] Stop using the `typo3/minimal` package on CI

composer.json
TYPO3 12LTS will require Doctrine ^3.3.7 (or possibly even higher).
To not block this, our development requirement of Doctrine needs to
allow Doctrine 3 as well.
=> [TASK] Allow dev installations with Doctrine 3

Tests/Unit/Controller/TeaControllerTest.php
Now all methods that conceptually should not be part of a controller
(and that hence must never be executed in a unit test)
are mocked for consistency.
Also sort the method names.
Fixes #446
=> [TASK] Also mock `redirectToUri` in the controller unit test

.github/dependabot.yml, composer.json
Also remove the update block from the Dependabot configuration (now that we require PHP >= 7.4., which allows for current versions of this package).
=> [TASK] Update ergebnis/composer-normalize

.github/dependabot.yml
The PRs now should target 3.0.0, not 2.0.1 anymore, as 2.0.1 is out of the door, and we're working on 3.0 now.
Fixes #583
=> [TASK] Switch Dependabot PR target milestone to the 3.0 milestone

CHANGELOG.md, Classes/Controller/TeaController.php, Classes/Domain/Model/Product/Tea.php, Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php, Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php, Tests/Unit/Domain/Model/Product/TeaTest.php, Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
The `@var` annotations where left where it is not possible yet to replace them in PHP 7.4.
Fixes #550
=> [CLEANUP] Use typed properties instead of `@var` annotations

CHANGELOG.md, composer.json
We're using a class from this package in the controller and hence should have this package as a direct dependency.
=> [BUGFIX] Stop relying on transitive dependencies for `psr/http-message`

.github/workflows/ci.yml
This way, the Composer dependencies are consistently in ascending order in the CI matrix (as are the PHP and TYPO3 versions).
Fixes #578
=> [TASK] Have the lowest dependencies above the highest on CI

composer.json
With PHP 7.4 as the minimum supported PHP version, we can now upgrade.
Also drop a now-obsolete conflict for a package version that now is not possible anymore.
=> [TASK] Upgrade `friendsofphp/php-cs-fixer`

CHANGELOG.md, composer.json
Now the Symfony (dev) dependencies are in sync what TYPO3 11LTS and 12LTS require.
=> [TASK] Bump the Symfony dependencies

composer.json
The removed conflicting versions are not possible anymore with our current set of dependencies.
=> [TASK] Remove obsolete Composer conflicts

.github/dependabot.yml
Dependabot cannot handle multi-version dependencies and would happily throw away one of allowed versions (like in #626).
=> [BUGFIX] Exclude `doctrine/dbal` from Dependabot updates

composer.json
This is required to get the tests to work with typo3/composer-installers V4/V5.
=> [TASK] Add the testing framework bridge as dev dependency

CHANGELOG.md, composer.json
This unblocks the road to Symfony 6 (which is required for TYPO3 12).
=> [TASK] Upgrade to `helmich/typo3-typoscript-lint` V3

.gitignore, CHANGELOG.md
JetBrains created a new product named "Fleet" as
lightweight editor. This tool tends to write it's
config files to `.fleet/` folders, like all of the IntellJ based IDE's like PHPStorm uses the `.idea` folder.
This change adds this config folder to `.gitignore` to avoid adding this folder to a patch if Fleet
is used to create a patch.
=> [TASK] Add `.gitignore` entry for JetBrains Fleet editor

CHANGELOG.md, composer.json
This package does not ship a `composer.lock`, and hence `composer normalize` should not check that file.
Fixes #640
=> [BUGFIX] Do not check `composer.lock` during `composer normalize`

.github/workflows/codecoverage.yml, .gitignore, CHANGELOG.md, composer.json
Case-insensitive filesystems cannot distinguish properly for file and folder names with different casings. This leads to unforseeable issues on these systems, like default partition on MacOS devices from apple or eventually Windows systems.
This change configure phpcoverall and the chain explicitly to use folders for the files which differs from the default of `build/*` to avoid conflicts on case-insensitve filesystems and prepare for introduction of the upcoming implementation of TYPO3 core recommended `Build/` structure.
=> [TASK] Avoid race condition on case-insensitive filesystems

CHANGELOG.md, Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Starting with TYPO3 12.1, a request is required for the `BackendConfigurationManager` to not crash:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/76447
Also, a fix in that area has been merged (after the release of TYPO3 12.1) that might allow us to remove our workaround again once we've updated to TYPO3 12.2 or 12.1.3:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/77028
=> [BUGFIX] Get the functional tests to work with TYPO3 >= 12.1

.github/workflows/ci.yml, .github/workflows/predefined.yml, .gitlab/pipeline/jobs/func-php8.1-v12-highest.yml, .gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml, .gitlab/pipeline/jobs/unit-php8.1-v12-highest.yml, .gitlab/pipeline/jobs/unit-php8.1-v12-lowest.yml, CHANGELOG.md, composer.json
TYPO3 12.1 has been released. So the 12.0 sprint release is no longer relevant.
=> [TASK] Set the minimal 12LTS version to 12.1

Documentation/Introduction.rst
Some might find the extension name confusing.
We therefore explain why we don't add _example or something else.
Resolves: #692
=> [TASK] Explain the extension name

.github/workflows/ci.yml, CHANGELOG.md
Now dependency updates by Dependabot will be automerged if/when all required checks are green.
This will reduce the repetetive work of merging all these update PRs, and we have been heavily relying on our CI pipeline to check if a depenceny update is safe to merge anyway.
Attaching any of the labels `wip` or `blocked` to a PR will block the automerging.
=> [FEATURE] Add automerging of green Dependabot PRs

.github/workflows/automerge.yml, .github/workflows/ci.yml
Our current automerging CI task does not work reliably.
So instead of using a GitHub Action that does the automerging itself, we are now using a GitHub Action that only triggers GitHub's own automerge feature (which works a lot more reliably).
=> [TASK] Switch to using GitHub's own automerge feature

.github/workflows/codecoverage.yml, composer.json
The following are changed:
- web-dir: ".Build/public" => ".Build/Web"
- bin-dir: not specified, defaulted to .Build/vendor/bin => ".Build/bin"
The vendor-dir was alreaday ".Build/vendor" and is left unchanged.
Since the above paths may be used in scripts, composer.json, build pipelines, configuration etc. it facilitates contribution across various extensions (and the core) if the same defaults are used.
The goal of patches related to #802 is to unify the paths across TYPO3 extensions, specifically focusing on the "official" extensions (such as tea, Documentation examples extension etc.).
- .Build has already been well established (and is used by "tea" as well.
- web-dir (".Build/Web") is currently not used consistently (across official extensions). Either ".Build/public", ".Build/Web" or …
=> [TASK] Unify web-dir, bin-dir

Classes/Domain/Model/Product/Tea.php
Apart from this small polish, there is nothing to change in order to be consistent with the latest decision on type annotations as described here:
https://decisions.typo3.org/t/phpstan-specific-phpdoc-annotations-in-the-core-code-base/807
Fixes #794
=> [CLEANUP] Reorder the type annotations for better readability

.github/workflows/auto-approve.yml
This way, we can enforce having an approval before a PR is allowed to get merged.
=> [FEATURE] Automatically approve Dependabot pull requests

.github/workflows/ci.yml, .github/workflows/predefined.yml, .gitlab/pipeline/jobs/func-php8.1-v12-highest.yml, .gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml, .gitlab/pipeline/jobs/func-php8.2-v12-highest.yml, .gitlab/pipeline/jobs/func-php8.2-v12-lowest.yml, .gitlab/pipeline/jobs/unit-php8.1-v12-highest.yml, .gitlab/pipeline/jobs/unit-php8.1-v12-lowest.yml, .gitlab/pipeline/jobs/unit-php8.2-v12-highest.yml, .gitlab/pipeline/jobs/unit-php8.2-v12-lowest.yml, composer.json
TYPO3 12.4 AKA 12LTS has been released.
=> [TASK] Bump the TYPO3 12 dependency from ^12.3 to ^12.4

composer.json
Even for a constraint like `^6.2`, we explicitly state the bug-fix version `^6.2.0`. Even though this is semantically the same, this communicates to the human reader that we explicitly allow version 6.2.0 instead of "any 6.2 version".
For dev dependencies that are also transitive dependencies of `typo3/cms-core`, align our dependencies with the `typo3/cms-core` dependencies. This allows us to catch bugs with the lowest dependencies that would go unnoticed if we required a higher version as a dev depdency.
=> [TASK] Make the development dependencies more specific

ext_localconf.php
After dropping TYPO3 10.4 support:
- Using an anonymous function is not needed anymore
- declare(strict_types=1); can and should be used
- Use statements instead of FQN should be used
resolves https://github.com/TYPO3-Documentation/tea/issues/826
=> [TASK] Cleanup ext_localconf.php

Classes/Domain/Model/Product/Tea.php, Classes/Domain/Repository/Product/TeaRepository.php, Configuration/Extbase/Persistence/Classes.php, Configuration/TCA/tx_tea_domain_model_product_tea.php, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Tests/Functional/Domain/Repository/Fixtures/Product/Tea.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithOwner.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithoutOwner.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TwoTeasWithOwner.csv, Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php, Tests/Unit/Domain/Model/Product/TeaTest.php, ext_tables.sql
This is a pre-patch for adding a CRUD plugin for tea records.
This property contains only the UID of the owner FE user, but not a relation to a FE user model. This is because we neither have nor need a FE user model for the purposes of the CRUD plugin.
=> [FEATURE] Add `Tea.ownerUid`

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/Tea/Index.html
Label keys should be specific to their context. This allows having different labels for the same thing in different contexts (e.g., having different headings for the tea title in the regular list view and the FE editor).
We take the plugin as the context here, which allows us to reuse labels between different actions of the same plugin (e.g., between the list view and single view).
=> [TASK] Restructure the label keys

Resources/Private/Templates/Tea/Index.html
The `scope` attribute only makes sense for `th` elements, but not for `td` elements.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td
=> [TASK] Drop incorrectly placed `scope` HTML attribute

Classes/Domain/Model/Product/Tea.php
The maximum length of the string fields ensures that the contents
fit within the limits of the corresponding DB columns.
=> [FEATURE] Add validation to the FE-editable tea properties

Tests/Unit/Controller/TeaControllerTest.php
In TYPO3 12LTS, this method still exists. So we are still able to mock it.
=> [BUGFIX] Allow `ActionController::redirect` in tests again

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/FrontEndEditor/Index.html, Tests/Unit/Controller/FrontEndEditorControllerTest.php, ext_localconf.php
The delete action is triggered using a form with a submit button, causing a POST request to be sent instead of a GET request. This is because GET requests should not modify (or delete) data, but only read it and be idempotent. Also, the request then is guaranteed to not get cached.
From a usability perspective, a button instead of a link also is semantically more correct: A link is expected to bring you to some place, whereas a button is expected to trigger some action.
Closes #871
=> [FEATURE] Add a delete functionality for the Tea FE editor

Classes/Controller/FrontEndEditorController.php
When creating a new tea record in the FE, or when editing one, the tea model provided to the form is not necessarily valid (and we need to accept invalid models if the following action rejects the model due to a valiation error).
=> [BUGFIX] Skip validation where validation makes no sense

.gitattributes, .gitignore, Build/Scripts/runTests.sh, composer.json
TYPO3 Core and related repositories like the `typo3/testing-framework`
or `typo3/styleguide` uses a bash script arround docker to execute all
scripts over different operating systems in a controlled and ensured
manner. This helps to reproduce locally failing jobs from a CI like
GitHub actions or GitLab.
TYPO3 core dropped recently the requirement for `docker-compose`,
reducing it to `docker` and preparing for dual usage with docker
and podman in the future.
This change integrates the current state as extension wrapper,
aligning contained suits with existing tools. Additionally, a
TYPO3 core version switch is integrated.
The added script is excluded from git archive building and    
during releasing.
A list of possible options can be display with:
```shell
Build/Scripts/runTests.sh -h
``` …
=> [FEATURE] Integrate `runTests.sh` execution wrapper - round one

composer.json
The new runTests.sh relies on the ghcr.io image. However the image itself relies on a non-prefixed version of the image. Thus, the image can't be pulled automatically, because it needs to be tagged afterwards.
fixes #903
=> [REGRESSION] Use ghcr docs render image

CHANGELOG.md, Classes/Domain/Model/Product/Tea.php, composer.json, phpstan.neon
=> Add type coverage

Tests/Functional/FunctionalTests.xml, Tests/Unit/UnitTests.xml, composer.json
=> [TASK] Use own configuration files for tests

Tests/Unit/Controller/TeaControllerTest.php
This way, the purpose of the stub/mock is more explicit.
Fixes #870
=> [TASK] Use more stubs in the unit tests

.gitlab/pipeline/.gitlab-ci.yml
The legacy License Compliance analyzer was deprecated in GitLab 15.9 and removed in GitLab 16.3. Bugs and vulnerabilities in this legacy analyzer will no longer be fixed. This error message can be resolved by removing Jobs/License-Scanning.gitlab-ci.yml from your CI configuration.
https://git.typo3.org/qa/example-extension/-/jobs/2694908
=> [TASK] Remove deprecated license scanning

Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
This makes the purpose of the mock/stub more explicit.
=> [CLEANUP] Convert one more mock to a stub

Tests/Unit/Controller/FrontEndEditorControllerTest.php, Tests/Unit/Controller/TeaControllerTest.php
This makes the purpose of the test doubles more clear to the reader.
Fixes #986
=> [CLEANUP] Use more stubs instead of mocks

Tests/Functional/Domain/Repository/Fixtures/Product/PersistedTea.csv, Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
This makes the corresponding test a lot more concise and easier to read.
=> [TASK] Migrate DB queries to CSV assertions in the functional tests

Tests/Functional/Domain/Repository/Fixtures/Product/Tea.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TeaOnPage.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithAllScalarData.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithImage.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithoutOwner.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TwoTeasWithOwner.csv, Tests/Functional/Domain/Repository/Fixtures/Product/TwoUnsortedTeas.csv, Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
This makes the fixture more minimal and reduces cross-dependencies between tests.
Also consistently avoid quotes for integer data in CSV DB fixtures.
Fixes #988
=> [TASK] Split up the DB fixtures for the functional tests

composer.json
The symlinking is no longer necessary, thanks to
https://github.com/TYPO3/testing-framework/pull/434
Resolves: #1000
=> [TASK] Remove obsolete symlink for functional tests

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
The tests now respect the TYPO3 extension key as well as the composer package name.
There is no more need to use the old (no longer used) typo3conf/ext path.
Resolves: #739
=> [CLEANUP] Migrate typo3conf path to composer package name

.gitlab/pipeline/jobs/func-php7.4-v11-highest.yml, .gitlab/pipeline/jobs/func-php7.4-v11-lowest.yml, .gitlab/pipeline/jobs/func-php8.0-v11-highest.yml, .gitlab/pipeline/jobs/func-php8.0-v11-lowest.yml, .gitlab/pipeline/jobs/func-php8.1-v11-highest.yml, .gitlab/pipeline/jobs/func-php8.1-v11-lowest.yml, .gitlab/pipeline/jobs/func-php8.1-v12-highest.yml, .gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml, .gitlab/pipeline/jobs/func-php8.2-v11-highest.yml, .gitlab/pipeline/jobs/func-php8.2-v11-lowest.yml, .gitlab/pipeline/jobs/func-php8.2-v12-highest.yml, .gitlab/pipeline/jobs/func-php8.2-v12-lowest.yml, .gitlab/pipeline/jobs/unit-php7.4-v11-highest.yml, .gitlab/pipeline/jobs/unit-php7.4-v11-lowest.yml, .gitlab/pipeline/jobs/unit-php8.0-v11-highest.yml, .gitlab/pipeline/jobs/unit-php8.0-v11-lowest.yml, .gitlab/pipeline/jobs/unit-php8.1-v11-highest.yml, .gitlab/pipeline/jobs/unit-php8.1-v11-lowest.yml, .gitlab/pipeline/jobs/unit-php8.1-v12-highest.yml, .gitlab/pipeline/jobs/unit-php8.1-v12-lowest.yml, .gitlab/pipeline/jobs/unit-php8.2-v11-highest.yml, .gitlab/pipeline/jobs/unit-php8.2-v11-lowest.yml, .gitlab/pipeline/jobs/unit-php8.2-v12-highest.yml, .gitlab/pipeline/jobs/unit-php8.2-v12-lowest.yml
Some GitLab jobs seem to run commands that do not belong in the the corresponding job.
This change outputs the job name in CI in order to help us track this down.
Related: #976
=> [TASK] Output the job name in the GitLab CI builds

.gitlab/pipeline/jobs/func-php8.2-v12-lowest.yml
The job name did not match the file name and the actual content of the job.
Relates: #976
=> [BUGFIX] Wrong GitLab job name

CHANGELOG.md, Configuration/TCA/tx_tea_domain_model_product_tea.php, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf
Resolves: #553 
Tested on v12 and v11
=> [FEATURE] Make records timeable and hidable

Build/Scripts/runTests.sh
`Build/Scripts/runTests.sh` provides a test-suite
`composer` and allows passing additional command
and options directly down to the composer command.
Due to an invalid quoting the passed options were
broking and not regonized by the `composer` binary.
This change removes the superflous argument passing
and therefore allows passing additional options to
the `composer` command.
Resolves: #967
=> [BUGFIX] Remove invalid argument quoting in `runTests.sh`

Configuration/TCA/Overrides/tt_content.php
select_key does not exist anymore in the Core and can be safely removed,
=> Remove leftover select_key

composer.json
This prevents the occasional "directory could not be created" failure when running the functional tests on CI.
Fixes #1053
=> [BUGFIX] Create required directories before running the functional tests

composer.json
The document root for the tests is `.Build/Web`, not `.Build/public`.
Followup to #1058
=> [FOLLOWUP] Fix path of created tests directory

composer.json
Some Composer scripts do not make sense as they call other scripts that only make sense when called separately. This change removes those multi-scripts that are practically useless.
=> [TASK] Drop useless Composer scripts

composer.json
It is not necessary to specify the file name of the baseline file if we're using the default file.
=> [CLEANUP] Simplify the PHPStan baseline generation script

composer.json
As we are now using CSV assertions in the functional tests instead of direct database queries, we do not require Doctrine DBAL in the tests anymore.
=> [TASK] Drop obsolete Doctrine DBAL development dependency

Build/Scripts/runTests.sh
TYPO3 provides core testing docker images which
the core itself uses for the Core testing. Core
stopped publishing new image builds to the docker
hub already and only publish to the GitHub container
registry in the future.
Therefore, the image prefix switch between CI and
local does not make sense anymore.
This change removes the image prefix variables and
use public images directly from docker hub and the
core testing images from the TYPO3 `ghcr.io` repo.
Resolves: #1066
Related: #969
=> [TASK] Use only ghcr.io for core-testing images

Build/Scripts/runTests.sh
The adopted `Build/Scripts/runTests.sh` contains traces
of acceptance and acceptanceInstall, mainly in the help
text.
The occurances are left-overs from the adoption phase
and are now removed due to the fact they are currently
not available at all.
Resolves: #1068
Related: #969
=> [TASK] Remove `acceptance` test traces from `runTests.sh`

composer.json
Also use stricter exclusion paths to avoid skipping JSON files that we actually want to lint.
This change speeds up JSON lint a lot in cases where Composer from within `runTests.sh` has been used (which creates the `.cache/` directory).
Fixes #1046
=> [BUGFIX] Avoid JSON-linting the Composer cache directory

Build/Scripts/runTests.sh
The TYPO3 core testing images only adds stuffs which is
required for the core testing itself and which can be
considered as generic project and extension testing
requirement.
This extension uses advanced `find` options which are
not part of the base busybox provided tools used by
the alpine base image, for example for the `lintYaml`
command in `Build/Scripts/runTests.sh`.
The used `-regextype` option of the `find` binary does
not exists in the stripped down busybox implementation
used by the alpine base images. The `findutils` package
is required to provide the gnu `find` command supporting
this and other advanced options, which can be found as
a solution here:
https://github.com/nextcloud/docker/issues/282
Due to the fact that the additional package will not
make the way into the TYPO3 …
=> [BUGFIX] Use extended `sbuerk/demo-core-testing-*` images

Build/Scripts/runTests.sh
With 8a2e0cb the `-b` option to select the container
binary (podman or docker) has been added. During the
adoption from the TYPO3 core implementation, it has
been discoverd that the simplified checks are not
really working and changed to the better supported
version.
Sadly, it have been missed to do the at all places
correctly.
This change covers that and modifies `runTests.sh`
to use the better supported condition form for the
container binary checks introduced with 8a2e0cb.
For example, conditions like
```shell
if [ ${CONTAINER_BIN} = "" ]; then ..
```
are changed to
```shell
if [ "${CONTAINER_BIN}" == "" ]; then ..
```
Resolves: #1085
=> [BUGFIX] Use better supported condition checks in `runTests.sh`

Build/Scripts/runTests.sh
The TYPO3 core runTests.sh has been using the
uid option for the tmpfs mount in the past
and removed it due to the fact it's not supported
by the podman container binary.
This has been missed to change along with the
introduction of the `-b` container binary option
in #1075 and therefore the podmand and docker dual
support.
For example, following
```shell
--tmpfs ${ROOT_DIR}/typo3temp/var/tests/functional-sqlite-dbs/:rw,noexec,nosuid,uid=${HOST_UID}
```
is changed to
```shell
--tmpfs ${ROOT_DIR}/typo3temp/var/tests/functional-sqlite-dbs/:rw,noexec,nosuid
```
which works for both binaries in case of tmpfs mounts.
Resolves: #1087
Resolves: #1083
Related: #1075
=> [BUGFIX] Avoid unsupported option for `podman`

Build/Scripts/runTests.sh
The TYPO3 core `runTests.sh` contains the `-u` option to
update the images and remove dangling images. Providing
an image name and a `--filter` option is not supported
by podmand and has not been discovered yet in the TYPO3
core implementation yet - and adopted with the recently
sync of this repository implementation to the TYPO3 one.
Both supported docker binaries `docker` and `podman`
supportes filtering images using the `reference` filter
option. Therefore, this change modifies the dangling
image remove command to use double filter options.
To verify that double filtering can be used, following
command can be executed if already some images have
been downloaded:
```shell
podman images \
--filter "reference=ghcr.io/sbuerk/demo-core-testing-*"
--filter "dangling=false" --format "{{.ID}}" …
```
=> [BUGFIX] Ensure removing dangling images works with `podman`

Tests/Functional/FunctionalTests.xml, Tests/Unit/UnitTests.xml
We already had this for unit tests, but it was missing for functional tests.
=> [TASK] Add coverage configuration for functional tests

Build/Scripts/runTests.sh
=> [TASK] Make TYPO3 12LTS the default in `runTests.sh`

.gitattributes, Configuration/FunctionalTests.xml, Configuration/UnitTests.xml, composer.json
The `Tests/` directory should only include test code, but not the configuration files.
Fixes #1082
=> [TASK] Move the PHPUnit configuration files to `Configuration/`

Tests/Functional/Controller/TeaControllerTest.php
This method is deprecated. Starting with TYPO3 11LTS, `executeFrontendSubRequest` should be used.
=> [TASK] Migrate the deprecated `executeFrontendRequest` in tests

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Classes/Controller/TeaController.php, Classes/Domain/Model/Tea.php, Classes/Domain/Repository/TeaRepository.php, Configuration/Extbase/Persistence/Classes.php, Configuration/TCA/tx_tea_domain_model_tea.php, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Language/pl.locallang_db.xlf, Tests/Functional/Controller/Fixtures/Database/Teas.csv, Tests/Functional/Domain/Repository/Fixtures/PersistedTea.csv, Tests/Functional/Domain/Repository/Fixtures/TeaOnPage.csv, Tests/Functional/Domain/Repository/Fixtures/TeaWithAllScalarData.csv, Tests/Functional/Domain/Repository/Fixtures/TeaWithImage.csv, Tests/Functional/Domain/Repository/Fixtures/TeaWithOwner.csv, Tests/Functional/Domain/Repository/Fixtures/TeaWithoutOwner.csv, Tests/Functional/Domain/Repository/Fixtures/TwoTeasWithOwner.csv, Tests/Functional/Domain/Repository/Fixtures/TwoUnsortedTeas.csv, Tests/Functional/Domain/Repository/TeaRepositoryTest.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php, Tests/Unit/Controller/TeaControllerTest.php, Tests/Unit/Domain/Model/TeaTest.php, Tests/Unit/Domain/Repository/TeaRepositoryTest.php, ext_tables.sql
The `Product` namespace segment in the domain model namespace `TTN\Tea\Domain\Model` currently serves no purpose and only adds confusion. So let's simplify the extension structure accordingly.
(I intended to use this to demonstrate DDD contexts, but never built enough models in the Tea extension for this to actually make sense.)
Fixes #1008
=> [!!!][TASK] Drop additional namespace segment for the Tea model

Build/Scripts/runTests.sh
=> [BUGFIX] Use our own PHPUnit configuration files in `runTests.sh`

Tests/Functional/Domain/Repository/TeaRepositoryTest.php
When the ordering of items (by title) is verified, checking the title instead of the UID makes this more clear.
Fixes #1132
=> [TASK] Rework a test communicate its purpose more clearly

.gitlab/pipeline/.gitlab-ci.yml, .gitlab/pipeline/jobs/php-cs-fixer.yml
I've just noticed that PHP CS Fixer is only executed on GitHub but not on GitLab
=> [TASK] Add PHP CS Fixer to GitLab

phpstan.neon
There were mixed indentation levels.
Those are now streamlined to level of 2.
This follows the existing convention for yaml files.
=> [TASK] Streamline indentation levels of phpstan.neon

composer.json, phpstan.neon
A new composer package "spaze/phpstan-disallowed-calls" is added. This one is a PHPStan extension which will check for forbidden calls. Those calls need to be defined per project.
We use this to prevent debugging and other none good practices from showing up in our code base.
We include the pre defined rules from the package. Those can be argued and adjusted once we hit them.
Resolves: #1158
=> [TASK] Add PHPStan extension for disallowed calls

.github/workflows/ci.yml, .github/workflows/predefined.yml, .gitlab/pipeline/jobs/build-composer-dependencies.yml, composer.json
This is a TYPO3 extension, a library.
We do not track the `composer.lock` file for that reason. Composer itself offers an option to prevent generation of the file. This is now configured to prevent the creation of the file.
That should prevent issues with local version of the file. One might change the `composer.json` version constraints but updates might fail due to locked version constraints.
This no longer happens if no locked version, due to missing lock file, exist.
=> [TASK] Prevent composer.lock file

composer.json
Lower versions of `webmozart/assert` do not play nice with PHP 8.2/8.3 in our tests.
So require the higher version.
=> [BUGFIX] Avoid warnings in PHP 8.2/8.3 with lowest dependencies

Tests/Functional/Controller/TeaControllerTest.php
To be closer to a real-world scenario, we also should load the constants of fluid_styled_content and the constants and setup of our own extension.
=> [BUGFIX] Load realistic, full TypoScript in the controller tests

phpstan.neon
This entry is not required - PHPStan already uses the Composer autoloader.
Fixes #1245
=> [TASK] Drop redundant bootstrap information from PHPStan config

phpstan-baseline.neon, phpstan.neon
These assertions are useful in tests also in cases where we have the corresponding type annotations in the production code.
Part of #1252
=> [TASK] allow `assertInstanceOf` checks for PHPStan

Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf
The concept of translation approval only applies to translated labels, not to the original labels in English.
Fixes #1257
=> [TASK] Drop `approved="yes"` from the original locallang files

Build/Scripts/runTests.sh, CHANGELOG.md
This change adds support for Postres 16 to the
`Build/Scripts/runTests.sh` execution wrapper.
[1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/82761
Resolves: #1147
Related: #94
=> [TASK] Add support for Postgres 16 to `runTests.sh`

Build/Scripts/runTests.sh
The `Build/Scripts/runTests.sh` has been streamlined recently
towards the `docker-compose less` approach of the TYPO3 core.
That means, that the `runTest.sh` has been heavily modified,
and multiple changes in the core variant has been implemented.
One of these changes included streamlining the Database Version
handling for the different vendors and combining multiple options
into the `-i` option and using a generic version variable instead
of vendor specific ones. Sadly, it has been missed to align the
version output on the end to the generic variable name.
This change modifies the dbms version output at the end of the
functional test execution to use the correct generic version
variable and thus fixing the missing version information in the
output. The switch has been simplified in the …
=> [BUGFIX] Display dbms version for functional test execution

Build/Scripts/runTests.sh
In the PHP world there are only one driver for SQLite and
Postgres available. `runTests.sh` disallows to specify a
driver for SQLite or Postgres and therefore setting the
variable would make that check more complex.
This change modifies the driver information for SQLite and
Postgres to use hardcoded driver output to keep the cross
check for specifing a driver for these database vendors.
Resolves: #1278
=> [BUGFIX] Display static driver info for sqlite and postgres

Configuration/Services.php, Configuration/Services.yaml, Documentation/DivergencesToTypo3Core.rst, Documentation/DivergencesToTypo3Core/Attributes.rst, Documentation/DivergencesToTypo3Core/ServicesFiles.rst, Documentation/Index.rst
* Migrate existing configuration from yaml to php.
* Document why we did the switch and that using yaml or both is totally valid and conforms to best practices.
* Document why we are not using attributes but only `Services.php` right now.
Resolves: #1172
Relates: #1237
=> [TASK] Migrate from Services.yaml to Services.php

Build/Scripts/runTests.sh
Let's use the most performant available PHP version for local development.
=> [TASK] Use PHP 8.3 by default in `runTests.sh`

composer.json
`find` has different options in different operating
system implementations (gnu, macosx, busybox, ...).
This change modies the used find command and replace
`-regextype` and `-regex` for multiple file extension
for `ci:yaml:lint` composer script.
Note: That unblocks the ability to revert to the
TYPO3 core-testing-* images and avoid 3rd party
extended images installing `gnu find`.
Resolves: #1209
=> [TASK] Use only busybox compatible `find` options

Build/Scripts/runTests.sh
Extended core-testing image has been used to
support extended `find` options not provided
by the busybox implementation.
After streamlining used `find` command usages
towards a stripped down version with #1209 it
is now possible to use the TYPO3 core-testing
images directly.
This change modifes `Build/Scripts/runTests.sh`
to use `typo3/core-testing-*` images now.
Resolves: #1275
Related: #1209
=> [TASK] Use TYPO3 core-testing images directly

Build/Scripts/runTests.sh
The new php based rendering container has been added
recently to render the documentation. The image come
with a internal uid/gid switch to mitigate permission
issues with docker due to a missimplementation, which
podman not suffers by proper using the kernal namespacing.
This change ensures to create a folder before hand with
the correct permissions to mitigate this for docker. On
top of that, the external user set is added for the direct
invokiation and also the interactive switch to avoid failure
in CI context usages.
To avoid permission issues with previously created folder,
a `chown` command is added to ensure correct permission on
that folder.
Resolves: #1283
=> [BUGFIX] Enhance container documentation rendering

.gitattributes, composer.json, rector.php
This part of #851.
In later parts, we'll add a Rector wrapper to `runTests.sh` and a CI job, and apply possible changes suggested by Rector.
Part of #851
Closes #125
=> [FEATURE] Add Rector

.github/workflows/ci.yml, package.json
Also make the required Node.js and NPM versions in `package.json` more specific.
=> [BUGFIX] Specify the Node.js version for GitHub Actions

package.json
TYPO3 Extensions are GPL V2+.
This is already stated in LICENSE and composer.json. For some reason package.json had a different license, which is now streamlined.
Resolves: #1305
=> [TASK] Switch the license in the package.json to GPL V2

.github/dependabot.yml, composer.json
This is necessary as older versions block installation of Symfony 7
components.
We also keep 0.6 as 0.8 drops support for older Symfony versions
Resolves: #1113
=> [TASK] Allow installation of typo3/coding-standards 0.8.x

Build/phpunit/FunctionalTests.xml, Build/phpunit/UnitTests.xml
This is disabled by default and enabled with this change. This has the following effect:
- Deactivate automatic garbage collection using gc_disable() before the first test is run
- Trigger garbage collection using gc_collect_cycles() before the first test is run
- Trigger garbage collection using gc_collect_cycles() after each n-th test
- Trigger garbage collection after using gc_collect_cycles() after the last test was run
- Activate automatic garbage collection using gc_enable() after the last test was run
Resolves: #1328
=> [TASK] Enable PHPUnit garbage collector control

.gitattributes, .github/workflows/ci.yml, composer-unused.php, composer.json
typo3/cms-fluid and typo3/cms-frontend are ignored because of their indirect usage.
Fixes: #348
=> [FEATURE] Include composer-unused to find unused packages

Build/Scripts/runTests.sh
This change modifies the `Build/Script/runTests.sh` command dispatcher to allow passing composer options to the `composer install` subcommand, for example
Build/Scripts/runTests.sh -s composerInstall \
-- --prefer-source
Note that this is already possible using the generic `-s composer` dispatcher but would resolve some user confusion.
This aligns our implementation of runTests.sh with TYPO3 core, see: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84870
Resolves: #1346
=> [TASK] Allow additional composer options for `-s composerInstall`

.github/workflows/ci.yml, .gitlab/pipeline/.gitlab-ci.yml, .gitlab/pipeline/jobs/typoscript-lint.yml, Build/Scripts/runTests.sh, Documentation/Running.rst, composer.json
As ts is usually understood as TypeScript instead of TypoScript. TYPO3 itself also changed its file extension from `.ts` to `.typoscript`. We reflect that by adopting the script name.
Resolves: #1385
=> [TASK] Use typoscript instead of ts within script names

Build/phpunit/FunctionalTests.xml, Build/phpunit/UnitTests.xml
The PHPUnit configuration option `controlGarbageCollector` was introduced for PHPUnit 10 and 11 only and hence is not available for version 9 yet (the version we're using). So we cannot use this configuration option yet.
This reverts commit 7dea2ddc0beda039c4a7b4944dc1833e097d0a4b.
=> [BUGFIX] Remove unavailable PHPUnit configuration option

Build/Scripts/runTests.sh
You can now the command with `Build/Scripts/runTests.sh -s composerUnused`
=> [FEATURE] Add `composerUnused`  suite to `runTests.sh`

Build/Scripts/runTests.sh
=> [BUGFIX] No longer create not needed temp folder

.github/workflows/ci.yml, .gitlab/pipeline/jobs/javascript-lint.yml, package.json
Commands are now
npm ci:lint:js
npm fix:lint:js
npm ci:lint:style
npm fix:lint:style
=> [TASK] Rename npm commands to fit general naming scheme

.github/workflows/ci.yml, .gitlab/pipeline/jobs/javascript-lint.yml, package.json
The name of the command should reflect the type of file that gets linted.
This is a pre-patch to #1396.
=> [TASK] Rename the CSS lint npm command

Build/Scripts/runTests.sh
Additionally, a generic npm command has been added. 
See `runTests.sh --help` to explore the new commands `npm`, `lintStyle` and `lintJs`
Fixes #972
=> [FEATURE] Allow running npm based quality checks via `runTests.sh`

Build/Scripts/runTests.sh
The script actually does not exist.
Instead `cgl` will fix and adding `-n` will turn into try mode and only check.
=> [BUGFIX] Remove none existing cglFix

.github/workflows/ci.yml, Build/Scripts/runTests.sh
=> [FEATURE] Add shellcheck to Github pipeline

Build/Scripts/runTests.sh
`composer install` does not make sense as we do not have a composer.lock. One should use `composer update` instead. This is reflected by updating the script names.
Relates: #1412
=> [TASK] Rename composerInstall* scripts

Build/Scripts/runTests.sh
- sort some lists
- use the proper capitalization for PHPStan
=> [TASK] Polish the `runTests.sh` help

Build/Scripts/runTests.sh
The project doesn't have a `composer.lock`. That's why one should use `composer update` instead of `composer lock`.
This can be done by using the existing `-s composer` and appending `update.
Furthermore, the command itself was not documented or used anyway.
Relates: #1412
=> [TASK] Remove undocumented composerInstall

Documentation/Environment.rst
Add necessary blank line.
The indentation will be rendered as quote otherwise.
=> [BUGFIX] Broken rendering in docs

.github/workflows/codecoverage.yml, .gitignore, composer.json
Unfortunately, with the GitHub Action, we need to go back to using the path `build/logs/clover.xml` for the combined coverage file.
Closes #1431
=> [TASK] Switch to the Coveralls GitHub action

.github/workflows/codecoverage.yml, composer.json
As we'll need to have `build/logs/` for the merged coverage data anyway, there is no point to have the separate coverage files in `.Build/coverage/` instead of in `build/coverage/`.
Now the setup is more consistent.
Please note that this only affects the CI builds as we usually only collect coverage data there for the pull requests.
=> [TASK] Unify the coverage-related directories

composer.json
We're already removing the whole `Build/` directory in this script.
So there is no need to also remove the individual files in this directory.
=> [TASK] Remove redundancies in the `prepare-release` Composer script

.github/workflows/ci.yml
This will avoid that a hung job will consume up to 30 minutes of CPU time.
=> [TASK] Add a time limit to the documentation check on CI

.github/workflows/ci.yml, .gitlab/pipeline/.gitlab-ci.yml, .gitlab/pipeline/jobs/rector.yml, composer.json
=> [FEATURE] Add Composer scripts and a CI job for Rector

composer.json
Check for syntax errors with PHP lint first, then check for structural problems with Rector and PHPStan, and after that check the coding style.
=> [TASK] Reorder the PHP-related steps in the `ci:static` script

.github/dependabot.yml
We want to be able to easily recognize PRs/commits created by Dependabot.
Fixes #1498
=> [TASK] Configure Dependabot to create specific commit messages

Tests/Unit/Controller/FrontEndEditorControllerTest.php, Tests/Unit/Controller/TeaControllerTest.php
Explain that those tests are not best practice anymore, and that we're in the process of migrating them to functional tests.
Fixes #1499
=> [DOCS] Add comment for controller unit tests

Classes/Command/CreateTestDataCommand.php, Configuration/Services.php, Documentation/CommandController.rst, Documentation/Index.rst, Tests/Functional/Command/CreateTestDataCommandTest.php, Tests/Functional/Command/Fixtures/Database/ExistingTeas.csv, Tests/Functional/Command/Fixtures/Database/OtherExistingTeas.csv, Tests/Functional/Command/Fixtures/Database/OtherTeas.csv, Tests/Functional/Command/Fixtures/Database/Pages.csv, Tests/Functional/Command/Fixtures/Database/Teas.csv, Tests/Functional/Command/Fixtures/Database/TeasAfterDelete.csv, Tests/Functional/Command/Fixtures/Database/TeasAfterDeleteOtherExistingTeas.csv, phpstan.neon
Simple command to add test data for tea model with a console command. It's just the first try and should be extended by more data, translations, etc.
Resolves: #1120
=> [FEATURE] Add command controller to create test data

Tests/Functional/Controller/Fixtures/Database/ContentElementTeaIndex.csv, Tests/Functional/Controller/Fixtures/Database/SiteStructure.csv, Tests/Functional/Controller/TeaControllerTest.php
=> [TASK] Add functional tests for `showAction`

.php-cs-fixer.php
We now use `addRules()` method instead of fiddling around with an array of rules.
It allows us to overwrite existing rules, or even disable existing rules by setting them to `false`.
=> [TASK] Improve readability of php-cs-fixer configuration

composer.json
This allows us to make use of the latest bugfixes, particularly PHP compatibility fixes.
=> [TASK] Raise the minimum required TYPO3 12LTS version

Documentation/DependencyManager.rst
=> [DOCS] Extend PHIVE section in docs

Classes/Domain/Model/Tea.php
Now that we have removed support for TYPO3 11LTS, we can simplify some type annotations.
=> [TASK] Simplify some type annotations

Classes/Domain/Model/Tea.php, Tests/Functional/Domain/Repository/Fixtures/propertyMapping/TeaWithDeletedImage.csv, Tests/Functional/Domain/Repository/TeaRepositoryTest.php
`_loadRealInstance` will return `null` if the target of the association does not exist (anymore). We need to handle that case in a clean way.
Also use a dedicated folder for the fixture to make the fixture easier to find, and to discourage reuse of fixtures.
=> [BUGFIX] Improve type safety for lazy-loaded associations

composer.json, phpstan.neon
This package provides some opiniated PHPStan rules to make our code more explicit and easier to read.
https://github.com/rectorphp/type-perfect
As our code already is in pretty good shape, the new rules do not create any new warnings.
Also add some blank lines to the PHPStan configuration file to make it more readable.
Fixes #1335
=> [FEATURE] Add `rector/type-perfect` PHPStan rules

composer.json
=> [BUGFIX] Generate the PHPStan baseline in `Build/`

.gitlab/pipeline/jobs/.default.yml
The CI didn't had the PHP intl extension enabled.
We now use the existing `php.ini` also within the GitLab CI. This already enabled the already installed extension, and therefore allows to install the composer dependencies and pass the CI.
Resolves: #1354, #1636
=> [BUGFIX] GitLab CI Pipeline

.github/workflows/ci.yml, .gitlab/pipeline/.gitlab-ci.yml, .gitlab/pipeline/jobs/prepare-release.yml
This script tends to break when we move configuration files around. To prevent this in the future, we now check this script on CI.
=> [FEATURE] Test the `prepare-release` Composer script on CI

.github/workflows/ci.yml
This makes the badge in the README shorter. Also, it makes it easier to differentiate between the badge for GitHub Actions and the one for GitLab CI.
=> [TASK] Shorten the GitHub Actions CI job label

Classes/Controller/TeaController.php, Tests/Functional/Controller/TeaControllerTest.php, composer-unused.php
Properly trigger TYPO3 404 handling in case a none available tea was requested.
That might happen when old links to no longer existing teas are called. Or if people play around with the URL.
We also cover this new feature with a functional test.
Related: #1565
=> [FEATURE] Add proper 404 handling for tea detail action

.github/dependabot.yml, .github/workflows/ci.yml, Build/Scripts/runTests.sh, composer.json
As this component is not necessary in our setup yet. It is also easy to setup, so no need for us to showcase this.
Also this adds some extra complexity to our setup due to: https://github.com/paratestphp/paratest/issues/890 which was the trigger to remove the component.
Resolves: #1647
=> [TASK] Remove brianium/paratest

.github/workflows/ci.yml
Use runTests.sh file to excute php linting in github workflow.
Related: #982
=> [TASK] Switch to using `runTests.sh` for PHP linting in GitHub Actions

.github/workflows/ci.yml, .github/workflows/codecoverage.yml
This is a pre-patch to switching GitHub Actions to use `runTests.sh` for the unit and functional tests.
=> [TASK] Simplify the unit/functional tests CI matrix

.github/workflows/ci.yml
This will not be possible anymore when we switch CI to `runTests.sh`.
This is a pre-patch to switching unit and functional tests on GitHub Actions to `runTests.sh`.
=> [TASK] Do not show the Composer version on CI anymore

Tests/Functional/Controller/Assertions/Database/FrontEndEditorController/Update/UpdatedTea.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php
It is considered best practice to cover controllers via functional instead of unit tests.
We therefore migrate the existing unit tests to functional tests.
The migration is split into multiple batches for smaller changes. This one covers tests related to `updateAction()`.
Relates: #1569
=> [TASK] Migrate controller tests to functional tests (updateAction)

Build/Scripts/runTests.sh
The first argument after processing defined options has been stored into the variable `TEST_FILE`. This value was passed to PHPUnit based commands as last argument, defining the test case to execute (or a subset).
Removing this workaround and directly passing remaining options to the command makes special arguments like `-e` obsolete and unblocks more generic command passing.
This change removes this variable and passes all remaining arguments after option processing directly to the PHPUnit command and paves the way for future command improvements.
Note:   This makes the `-e` option basically obsolete, but
is kept for now to minimize muscle memory issues.
Using it will display a `deprecation` notice at the
end of the script - so it gets recognized.
This is the Tea port of this change in …
=> [TASK] Unblock argument passing in `Build/Scripts/runTests.sh`

.github/workflows/ci.yml
This tests failed in the past and now is green.
So let's re-enable it.
=> [TASK] Re-enable a skipped test on CI
