CHANGELOG.md
composer.json

Also update the GitHub URLs in the `composer.json`.
Fixes #2

[TASK] Change the Composer namespace to "ttn"

---

CHANGELOG.md
Classes/Controller/TeaController.php
Classes/Domain/Model/Product/Tea.php
Classes/Domain/Repository/Product/TeaRepository.php
Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
Configuration/TCA/Overrides/tt_content.php
Tests/Acceptance/StarterCest.php
Tests/Functional/Controller/TeaControllerTest.php
Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Tests/Unit/Controller/TeaControllerTest.php
Tests/Unit/Domain/Model/Product/TeaTest.php
Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
composer.json
ext_emconf.php
ext_localconf.php

[TASK] Convert the PHP namespaces to "TTN"

---

CHANGELOG.md
Classes/Controller/TeaController.php
Classes/Domain/Model/Product/Tea.php
Classes/Domain/Repository/Product/TeaRepository.php
Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
Tests/Acceptance/StarterCest.php
Tests/Acceptance/_support/AcceptanceTester.php
Tests/Acceptance/_support/Helper/Acceptance.php
Tests/Functional/Controller/TeaControllerTest.php
Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Tests/Unit/Controller/TeaControllerTest.php
Tests/Unit/Domain/Model/Product/TeaTest.php
Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
composer.json

Fix codesniffer issues

---

CHANGELOG.md
README.md

[BUGFIX] Update the badge URLs in the README

---

.github/workflows/ci.yml
.travis.yml
CHANGELOG.md

[TASK] Move PHP linting to GitHub actions

---

.github/workflows/ci.yml
.travis.yml
CHANGELOG.md

[TASK] Move PHP code sniffing to GitHub actions

---

.github/workflows/ci.yml
.travis.yml
CHANGELOG.md

[TASK] Move TypoScript linting to GitHub actions

---

CHANGELOG.md
README.md

Also fix some formatting issues.
Fixes #4

[TASK] Drop obsolete parts from the README

---

CHANGELOG.md
Tests/Unit/Controller/TeaControllerTest.php
Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
composer.json
phpcs.xml.dist

Also update the corresponding packages and autoformat the code again.
Fixes #3

[TASK] Switch the code sniffing from PSR-2 to PSR-12

---

.github/workflows/ci.yml
CHANGELOG.md

Cache dependencies during build

---

.github/workflows/ci.yml
.travis.yml
CHANGELOG.md

[TASK] Move unit test run to GitHub actions

---

CHANGELOG.md
ext_localconf.php

Move the plugin registration into a function.

[BUGFIX] Keep the global namespace clean in ext_localconf.php

---

.github/workflows/ci.yml

This reduces code duplication in the CI configuration file.
Fixes #63

[TASK] Use a matrix for the configuring the code quality checks

---

.github/workflows/ci.yml

[TASK] Run tests only if lint succeds

---

.gitlab-ci.yml

https://gitlab.typo3.org/qa/example-extension/-/pipelines/9370

[TASK] Add code quality stage

---

.github/workflows/ci.yml

[TASK] Reduce GitHub actions builds

---

composer.json

[TASK] Remove install-extension-dummy from composer.json

---

Resources/Private/Layouts/Default.html
Resources/Private/Templates/Tea/Index.html
Resources/Private/Templates/Tea/Show.html

[TASK] Use official xmlns in templates

---

.gitlab/pipeline/.gitlab-ci.yml

Resolves: #104 
https://gitlab.typo3.org/qa/example-extension/-/pipelines/9657

[TASK] Rework gitlab ci dependencies

---

.gitattributes

[TASK] Add gitattributes

---

README.md

Blocked, see #96 
Resolves: #96

[TASK] Add gitlab ci badge

---

.github/workflows/ci.yml
README.md
composer.json

Also update URLs to other repositories that also have done
the switch.

[TASK] Switch the default branch from master to main

---

composer.json

[BUGFIX] Always use the configuration file for php-cs-fixer

---

.php_cs.php
Configuration/TCA/Overrides/sys_template.php
Configuration/TCA/Overrides/tt_content.php
Configuration/TCA/tx_tea_domain_model_product_tea.php
composer.json

Rerun checks after merge of #122 
Resolves: #115

[TASK] Add more files to php sniffing and fixing

---

composer.json

I'm not sure if this is what you meant in issue, let me know :).
Resolves: #116

[TASK] Add one command to do sniffers and fixers

---

README.md

[TASK] Add feature list

---

.editorconfig

[FEATURE] Add a configuration for XML files to the .editorconfig

---

.github/workflows/ci.yml

This is the first part of #162 (which then will cover the functional
tests).

[CLEANUP] Explicitly set the Ubuntu version for most CI steps

---

.github/workflows/ci.yml

The key must not be split across multiple lines.

[BUGFIX] Fix cache keys for the Composer cache in GitHub Actions

---

.editorconfig
Resources/Public/JavaScript/Main.js

Also drop redundancies and sort the entries.

[CLEANUP] Adopt .editorconfig settings from the TYPO3 core

---

.github/workflows/ci.yml
.gitlab/pipeline/.gitlab-ci.yml
Configuration/TCA/Overrides/sys_template.php
Configuration/TsLint.yml
Resources/Private/.eslintrc.json
Resources/Private/.prettierrc.js
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/de.locallang_db.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf
Resources/Private/Templates/Tea/Index.html
Resources/Private/package.json
Resources/Private/stylelint.config.js
codeception.yml
composer.json
ext_tables.sql

This will reduce unrelated autoformatting changes in other commits
(and it also makes the code more readable).

[CLEANUP] Autoformat all files

---

.gitlab/pipeline/.gitlab-ci.yml

https://gitlab.typo3.org/qa/example-extension/-/pipelines/10130
please don't mind code_quality gitlab template job, as it's failing randomly due to no space on device, I think we should remove this job anyway.

[FEATURE] Add frontend linting to GitLab CI

---

.gitlab/pipeline/.gitlab-ci.yml

It's failing randomly on typo3 gitlab instance.

[TASK] Remove code quality job from GitLab CI template

---

.github/workflows/ci.yml

[BUGFIX] Fix the Composer cache directory in the CI configuration

---

composer.json

Update urls in composer json

---

.github/workflows/publish.yml
composer.json

[FEATURE] Add TER release via github actions

---

composer.json

Exclude node modules from yarn lint

---

README.md

[TASK] Update the manual URL in the README

---

.github/workflows/ci.yml

https://github.com/TYPO3-Continuous-Integration/TYPO3-CI-Yaml-Lint

[TASK] Migrate to yaml linter github actions

---

.github/workflows/ci.yml

https://github.com/TYPO3-Continuous-Integration/TYPO3-CI-Copy-Paste-Detector

[TASK] Migrate copy'n'paste detector to GitHub actions

---

.github/workflows/ci.yml
README.md
composer.json

Also sort the style checks in the GitHub Actions run.
Also improve some headings in the README.

[CLEANUP] Rename the CS fixer composer script

---

.github/workflows/ci.yml

https://github.com/TYPO3-Continuous-Integration/TYPO3-CI-Codestyle

[TASK] Migrate to github actions codestyle check

---

.github/workflows/ci.yml

https://github.com/TYPO3-Continuous-Integration/TYPO3-CI-Codesniff

[TASK] Migrate PHP CodeSniffer to GitHub Actions

---

composer.json

[BUGFIX] Fix tool path for fix:php:cs Composer command

---

composer.json

[BUGFIX] Dont check node modules in json lint

---

README.md

This patch adds a badge for the code of conduct to the readme like suggested at https://www.contributor-covenant.org/

[TASK] Add code of conduct badge to README

---

composer.json

[BUGFIX] Add conflict for doctrine/dbal

---

.ddev/commands/web/lint
.ddev/config.yaml
README.md

[FEATURE] Add base ddev setup and command

---

CODE_OF_CONDUCT.md
README.md

[TASK] Upgrade to CoC v2

---

.github/workflows/ci-composer-scripts.yml
.github/workflows/ci-scripts.yml
Documentation/Index.rst
Documentation/Linters/GitHub/Index.rst
Documentation/Linters/GitLab/Index.rst
Documentation/Linters/Index.rst
README.md

[TASK] Add separate workflow for composer scripts

---

.ddev/config.yaml
README.md

I upgraded ddev to 17.7.7 in this PR, on lower version it won't run properly. 
Resolves: #252

[TASK] Run functional tests in ddev

---

README.md

Fixes #144
Fixes #203
Fixes #241
Fixes #264
Fixes #265

[TASK] Completely rewrite the README

---

Classes/Controller/TeaController.php
Classes/Domain/Model/Product/Tea.php
Classes/Domain/Repository/Product/TeaRepository.php
Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
Tests/Acceptance/StarterCest.php
Tests/Functional/Controller/TeaControllerTest.php
Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Tests/Unit/Controller/TeaControllerTest.php
Tests/Unit/Domain/Model/Product/TeaTest.php
Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php

[TASK] Remove author annotations

---

.gitattributes
composer.json
phpstan-baseline.neon
phpstan.neon

- configure the checked paths via the configuration file
- do not output a progress bar on CI
- add a baseline file and a command for creating it
- cap the number of processes
Fixes #281

[TASK] Enhance the PHPStan configuration

---

Tests/Functional/Controller/TeaControllerTest.php
Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Tests/Unit/Controller/TeaControllerTest.php
Tests/Unit/Domain/Model/Product/TeaTest.php
Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php

[TASK] Always use `@covers` annotations in the tests

---

.github/workflows/ci.yml
composer.json
ext_emconf.php

[TASK] Start to work on TYPO3 v11 support

---

phpstan-baseline.neon
phpstan.neon

[TASK] Also check `Configuration/` and `Tests/` with PHPStan

---

Classes/Domain/Model/Product/Tea.php

[CLEANUP] Make lazy-loading proxies visible via type annotations

---

.gitattributes

Also re-sort the `.gitattributes` file.
Fixes #313

[TASK] Keep the PHPStorm meta file out of Composer packaging

---

.github/workflows/ci.yml
CHANGELOG.md

The functional tests still need some work, though.

[FEATURE] Also run the unit tests with V11 in the CI pipeline

---

composer.json

Also rearrange the entries in the `composer.json` according to the
updated version of `composer-normalize`.

[TASK] Update composer-normalize

---

.github/workflows/predefined.yml

Disable predefined github action scheduler run

---

.phpstorm.meta.php

[TASK] Update phpstorm meta file according to core

---

.phpstorm.meta.php

Copied from:
- https://review.typo3.org/c/Packages/TYPO3.CMS/+/73521
- https://review.typo3.org/c/Packages/TYPO3.CMS/+/73415
Fixes #382

[FEATURE] Add module definitions to the PhpStorm meta file

---

composer.json

Fix to code coverage calculation, related to #361

[BUGFIX] Fix code coverage calculation after switch to core testing framework

---

Classes/Domain/Repository/Product/TeaRepository.php

This helps static code analysis determine for which models the
repository is responsible.

[CLEANUP] Add generics annotation to the Tea repository

---

.ddev/php/custom-php.ini

[BUGFIX] Enable debugging in DDEV

---

.github/workflows/codecoverage.yml
.gitignore
CHANGELOG.md
README.md
composer.json

[FEATURE] Use Coveralls for the code coverage

---

Tests/Unit/Controller/TeaControllerTest.php

This helps static code analysis.

[CLEANUP] Make a type annotation in a unit test more specific

---

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php

Also add another type check to help with debugging failed queries.

[CLEANUP] Use prepared statements for SQL queries in the tests

---

README.md

[TASK] Add Slack to README

---

.editorconfig
CHANGELOG.md

refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/194

Change default rst indentation to 4 spaces

---

.phpstorm.meta.php
composer.json

[BUGFIX] Add hidden files to find in PHP lint

---

.ddev/config.yaml

[TASK] Update PHP in DDEV to 8.1

---

.github/workflows/ci.yml

This helps debug problems, e.g., using an incorrect Composer cache directory.

[FEATURE] Show the Composer configuration in the CI jobs

---

.github/workflows/ci.yml
.github/workflows/codecoverage.yml
.github/workflows/predefined.yml

[TASK] Upgrade the functional tests on CI to Ubuntu 22.04

---

CHANGELOG.md
Classes/Controller/TeaController.php
Tests/Unit/Controller/TeaControllerTest.php

resolves https://github.com/TYPO3-Documentation/tea/issues/564

[TASK] Return `ResponseInterface` in controller actions

---

Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php

[CLEANUP] Drop usages of `ObjectManager` whereever possible

---

CHANGELOG.md
Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
composer.json

This is required to also run the tests on TYPO3 12LTS.

[TASK] Upgrade to the testing framework V7

---

CHANGELOG.md
Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php

Stop injecting query settings

---

.github/workflows/ci.yml
.github/workflows/codecoverage.yml
.github/workflows/predefined.yml
.github/workflows/publish.yml
CHANGELOG.md

Harden Github Actions workflows

---

Documentation/Index.rst
Documentation/PHPVersionSupport.rst

[TASK] Document our approach to PHP version support

---

.github/workflows/ci.yml
.github/workflows/predefined.yml
.gitlab/pipeline/.gitlab-ci.yml
.gitlab/pipeline/jobs/func-php8.1-v12-highest.yml
.gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml
CHANGELOG.md

[FEATURE] Run the functional tests on TYPO3 12 as well

---

Configuration/TCA/Overrides/tt_content.php

[BUGFIX] Fix default controls override for plugin type

---

Configuration/TypoScript/constants.typoscript
Configuration/TypoScript/setup.typoscript

[BUGFIX] Use plural in the TypoScript template settings

---

Documentation/Introduction.rst

[TASK] Document that this is not a kickstarter package

---

.github/workflows/ci.yml
.gitlab/pipeline/.gitlab-ci.yml
.gitlab/pipeline/jobs/composer-psr-verify.yml
composer.json

Add check for PSR-4 namespace correctness

---

Configuration/TCA/tx_tea_domain_model_product_tea.php
Resources/Private/Language/de.locallang_db.xlf
Resources/Private/Language/locallang_db.xlf

[FEATURE] Allow to hide teas based on fe_groups

---

composer.json

[FEATURE] Add fix composer normalize command

---

Configuration/TCA/Overrides/tt_content.php

[TASK] Use anonymous function in TCA overrides

---

Configuration/TCA/tx_tea_domain_model_product_tea.php

Make the records localizable

---

.gitlab/build/docker_install.sh

https://git.typo3.org/qa/example-extension/-/pipelines/42493
Resolves: #789

[BUGFIX] Add missing PHP extensions in GitLab CI

---

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php

Tests should only test one thing (if possible).

[TASK] Make the repository tests more fine-grained

---

Tests/Unit/Controller/TeaControllerTest.php

Tests should only test one thing (if possible).

[TASK] Make the controller tests more fine-grained

---

Configuration/TCA/tx_tea_domain_model_product_tea.php

Also choose a formatting that does not change if someone autoformats the file in PhpStorm (which allows developers to work on the file more easily).

[CLEANUP] Polish the code formatting in the TCA configuration

---

CHANGELOG.md
Classes/Controller/FrontEndEditorController.php
Configuration/TCA/Overrides/tt_content.php
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Layouts/FrontEndEditor.html
Resources/Private/Templates/FrontEndEditor/Index.html
Tests/Unit/Controller/FrontEndEditorControllerTest.php
ext_localconf.php

This is one more part of building CRUD functionality.

[FEATURE] Add a list view for the FE tea editor

---

Classes/Controller/FrontEndEditorController.php
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Partials/FrontEndEditor/Form.html
Resources/Private/Partials/FrontEndEditor/ValidationResult.html
Resources/Private/Templates/FrontEndEditor/Edit.html
Resources/Private/Templates/FrontEndEditor/Index.html
Tests/Unit/Controller/FrontEndEditorControllerTest.php
ext_localconf.php

[FEATURE] Add FE editing for existing tea records

---

Classes/Controller/TeaController.php
Tests/Unit/Controller/TeaControllerTest.php

[TASK] Switch the `TeaController` to construtor injection

---

Documentation/ContinuousIntegration.rst
Documentation/Settings.cfg
README.md
composer.json
package.json

[TASK] Update repository urls

---

CHANGELOG.md

[TASK] Rename TsConfig directory

---

Tests/Unit/Controller/FrontEndEditorControllerTest.php
Tests/Unit/Controller/TeaControllerTest.php

Also reduce the cognitive load as these switches are between V12 and pre-V12.

[CLEANUP] Make the TYPO3 version switches more consistent

---

composer.json

Fix PSR-verify job for gitlab CI
https://git.typo3.org/qa/example-extension/-/jobs/2694886
it's failing in other builds

[BUGFIX] Fix PSR-verify job

---

.github/workflows/ci.yml
.github/workflows/predefined.yml

[TASK] Upgrade composer to 2.6 in github actions

---

.ddev/config.yaml
.github/workflows/ci.yml
.github/workflows/predefined.yml

This saves us changes to the configuration files each time a new Composer major version is released.

[TASK] Always use the latest Composer V2

---

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php

This makes the tests more concise while still keeping them readable.

[CLEANUP] Inline some variables in the tests

---

.ddev/config.yaml

This is a pre-patch to the changes for upgrading DDEV in #991.

[CLEANUP] Increase the indentation in the DDEV configuration file

---

Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php

Dedicated test cases were added in the past.
This test case was not added yet.
Resolves: #858

[TASK] Add missing test case for fetching none existing tea

---

CHANGELOG.md
Resources/Private/Language/pl.locallang.xlf
Resources/Private/Language/pl.locallang_db.xlf

[FEATURE] Provide Polish translation for tea

---

.gitlab/build/docker_install.sh

Resolves: #976 
This is related to different settings in error reporting.
https://git.typo3.org/qa/example-extension/-/commit/ccc186123268e8fc0af2cb3d6447d9eed8bc3394

Fix for functional tests on gitlab CI

---

Build/Scripts/runTests.sh

Until now three different dbmns version options
has been used like the TYPO3 core in older days.
This change aligns with the TYPO3 core and merge
these options together into one flag, keeping
`-i` for all dbms vendors now and dropping `-k`
for postgres and `-j` for mysql specific versions.
The help text is modified to align with the changed
options.
Resolves: #1062
Related: #969

[TASK] Merge dbms version flags into `-i`

---

.gitlab/pipeline/jobs/func-php8.3-v11-highest.yml
.gitlab/pipeline/jobs/func-php8.3-v11-lowest.yml
.gitlab/pipeline/jobs/func-php8.3-v12-highest.yml
.gitlab/pipeline/jobs/func-php8.3-v12-lowest.yml

Resolves: #1022 
last part of php8.3 implementation in gitlab
https://git.typo3.org/qa/example-extension/-/pipelines/50686

[TASK] Add php8.3 to functional tests gitlab

---

Build/Scripts/runTests.sh

TYPO3 core introduced the `-b` option for the
`Build/Scripts/runTests.sh` script to provide
the ability to select the container binary,
`docker` or `podman` and enforces podman for
CI (GitLab runner) runs after switching the
Core CI infrastructure from Docker-In-Docker
to Podman-In-Podman.
The `ext:tea` adoption of the `runTests.sh`
has been already adopted on a intermediate
version and dropped the `docker-compose`
based container definitions. Along with
other minor prepration patches this allows
now to add the container binary selection
also.
This change modifies `runTests.sh` to
* add the `-b` option with a corresponding
helptext addition and allows `podman` or
`docker` - whereas the latter is the default.
* integrates the determined and fixed issues
with tty in CI environments by …

[TASK] Add `-b` option to select container binary

---

Tests/Functional/FunctionalTests.xml
Tests/Unit/UnitTests.xml

This avoids unrelated formatting changes in functional changes.

[CLEANUP] Autoformat the PHPUnit configuration files

---

composer.json

This avoids unrelated changes when this list is modified.

[CLEANUP] Sort the files/directories in the `prepare-release` script

---

Build/Scripts/runTests.sh
composer.json

Resolves: #1140
It's blocked right now as it's breaking change.

[TASK] Change webdir of TYPO3 to public

---

.github/dependabot.yml

See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message

[TASK] Add a commit message prefix

---

Tests/Unit/Domain/Model/TeaTest.php

[TASK] Use unique and more realistic test data in the unit tests

---

CHANGELOG.md
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/de.locallang_db.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf
Resources/Private/Language/pl.locallang.xlf
Resources/Private/Language/pl.locallang_db.xlf

[BUGFIX] Add `resname` to all language labels

---

phpstan-baseline.neon
phpstan.neon

[TASK] Raise PHPStan to level 6

---

Classes/Domain/Repository/TeaRepository.php
phpstan-baseline.neon

This fixes the last remaining PHPStan level 6 warning.

[TASK] Improve the type annotations for `TeaRepository`

---

phpstan-baseline.neon
phpstan.neon

[TASK] Raise PHPStan to level 9

---

Classes/Controller/FrontEndEditorController.php
phpstan-baseline.neon

This fixes the last PHPStan level 9 warning.

[TASK] Narrow down a type in the controller

---

composer.json

[TASK] Add ci:xliff:lint to ci:static

---

Configuration/TCA/tx_tea_domain_model_tea.php

[TASK] Activate workspace support for tea model

---

Build/Scripts/runTests.sh

This change now uses a bash trap to ensure proper container
cleanup after some signals happend. The internal `waitFor()`
is modified to emit a signal to cleanup containers if the
waiting process does not process correctly and stop the
script execution.
Additionally, `--pull-never` as CI_PARAMS is no longer derived
from the `$CI` variable and must now be handed over from the
calling process.
Further, the max retry value in `waitFor()` is increased to 20
to mitigate the slowed down startup of MySQL 8.0 container.
Resolves: #1280

[BUGFIX] Ensure correct service waits and container cleanup

---

README.md

Communicate that we value and welcome feedback and the possible ways to provide feedback.
Resolves: #1236

[TASK] Add feedback section to readme

---

Documentation/Running.rst

[TASK] Document to use WSL for tests on Windows

---

Documentation/Assertions.rst
Documentation/Index.rst

[TASK] Document our approach to assertions and type checks

---

Build/phpunit/UnitTests.xml

Remove no longer needed bootstrap option.
Remove no longer needed backupGlobals options.
Resolves: #1347

[TASK] Clean up the unit tests configuration

---

Documentation/Environment.rst

[TASK] Add more development documentation

---

.github/workflows/ci.yml
composer.json

[FEATURE] Use parallel-lint for command ci:php:lint

---

Build/Scripts/runTests.sh

[FEATURE] Add support for PHP 8.4 in `runTests.sh`

---

composer.json

[FEATURE] Show memory consumption of phpstan

---

Build/Scripts/runTests.sh

[BUGFIX] Clean up network after invalid command

---

.gitlab/pipeline/.gitlab-ci.yml
.gitlab/pipeline/jobs/.composer-update.yml
.gitlab/pipeline/jobs/php-lint-php7.4.yml
.gitlab/pipeline/jobs/php-lint-php8.0.yml
.gitlab/pipeline/jobs/php-lint-php8.1.yml
.gitlab/pipeline/jobs/php-lint-php8.2.yml
.gitlab/pipeline/jobs/php-lint-php8.3.yml

Resolves: https://github.com/FriendsOfTYPO3/tea/issues/1455
Old pipeline: https://git.typo3.org/qa/example-extension/-/pipelines/65960
Pipeline after fix: https://git.typo3.org/qa/example-extension/-/pipelines/65970

[BUGFIX] Fix parallel lint in gitlab CI

---

package.json

[TASK] Set npm to version 10.8.2

---

Build/Scripts/runTests.sh

[TASK] Add if condition from core runTests.sh

---

Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/de.locallang_db.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf
Resources/Private/Language/pl.locallang.xlf
Resources/Private/Language/pl.locallang_db.xlf

It has turned out that this is not needed after all:
https://forge.typo3.org/issues/105647

[TASK] Remove unneeded `resname` from the language files

---

.php-cs-fixer.php

[BUGFIX] Avoid unsetting almost all PHP-CS-Fixes rules

---

Classes/Controller/FrontEndEditorController.php
Classes/Controller/TeaController.php
Classes/Domain/Model/Tea.php
rector.php

[TASK] Raise PHP Language Level to 8.1

---

Documentation/Running.rst

[DOCS] Improve docs for run tests

---

.gitlab/pipeline/jobs/php-cs-fixer.yml
.gitlab/pipeline/jobs/phpstan.yml
.gitlab/pipeline/jobs/rector.yml

Adapt them to the PHP linting jobs we actually run.

[BUGFIX] Fix GitLab CI job dependencies

---

Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Tea/Index.html
Tests/Functional/Controller/TeaControllerTest.php

[TASK] Cover empty tea index with functional test

---

composer.json

As preparation for TYPO3 v13 support.
Resolves: #1575

[TASK] Update typo3/testing-framework

---

Configuration/FlexForms/TeaIndex.xml
Configuration/TCA/Overrides/tt_content.php
Configuration/TypoScript/constants.typoscript
Configuration/TypoScript/setup.typoscript
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Tests/Functional/Controller/Fixtures/Database/ContentElementTeaIndex.csv
Tests/Functional/Controller/Fixtures/Database/SiteStructure.csv
Tests/Functional/Controller/Fixtures/Database/TeaInSubfolder.csv
Tests/Functional/Controller/Fixtures/TypoScript/Constants/PluginConfiguration.typoscript
Tests/Functional/Controller/TeaControllerTest.php

This is part 1.
(Part 2 is about migrating the storage page for new records created in the FE editor.)
Part of #1570

[FEATURE] Move the tea index configuration to FlexForms

---

.github/ISSUE_TEMPLATE/bug.md

feature: Add issue template for bug

---

.github/workflows/ci.yml

[TASK] Switch to using `runTests.sh` for code quality checks in GitHub Actions

---

.github/workflows/ci.yml

[TASK] Switch to using `runTests.sh` for `prepare-release` in Github Actions

---

.github/workflows/ci.yml

 [TASK] Switch to using `runTests.sh` for code quality frontend in GitHub Actions

---

.github/workflows/ci.yml

 [TASK] Switch to using `runTests.sh` for unit tests in GitHub Actions

---

Build/Scripts/runTests.sh

[DOCS] Document in `runTest.sh` that Podman now is the default

---

Documentation/Running.rst

[DOCS] Remove code coverage commands from docs

---

Documentation/Running.rst

[DOCS] Using `runTests.sh` also for composer commands

---

.github/workflows/ci.yml

This is a partial revert of
5464315104879626cd8573ac355a004e4f91c11a.
Fixes #1701

[TASK] Re-add showing the Composer version on CI
